version: '3'

services:

  app:
    build: .
    command: "uwsgi --ini ./uwsgi.ini"
    networks:
      - my-bridge

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my-bridge


networks:
  my-bridge:
    driver: bridge
