version: '3'

services:

  app:
    build: .
    command: "uwsgi --ini ./uwsgi.ini"
    networks:
      - my-bridge

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my-bridge

  redis:
    image: redis
    networks:
      - my-bridge

  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: my_vhost
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge
